In [47]:
#Maximum and Average poling

In [50]:
from mxnet import np, npx
from mxnet.gluon import nn
#from d2l import mxnet as d2l

In [51]:
npx.set_np()

In [63]:
def pool2d(X, pool_size, mode='max'):
  p_h, p_w = pool_size
  Y = np.zeros((X.shape[0] - p_h + 1, X.shape[1] - p_w + 1))
  for i in range(Y.shape[0]):
    for j in range(Y.shape[1]):
      if mode == 'max':
        Y[i, j] = X[i:i + p_h, j:j + p_w].max()
      elif mode == 'avg':
        Y[i, j] = X[i:i + p_h, j:j + p_w].mean()
  return Y


In [64]:
#For maximum
X = np.array([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
pool2d(X, (2, 2))


array([[4., 5.],
       [7., 8.]])

In [65]:
#for average
pool2d(X, (2, 2), 'avg')


array([[2., 3.],
       [5., 6.]])

In [66]:
### Padding and Stride

In [67]:
X = np.arange(16, dtype=np.float32).reshape((1, 1, 4, 4))
X

array([[[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]]]])

In [68]:
pool2d = nn.MaxPool2D(3)
# Because there are no model parameters in the pooling layer, we do not need
# to call the parameter initialization function
pool2d(X)

array([[[[10.]]]])

In [70]:
pool2d = nn.MaxPool2D(3, padding=1, strides=2)  #The stride and padding can be manually specified
pool2d(X)

array([[[[ 5.,  7.],
         [13., 15.]]]])

In [71]:
pool2d = nn.MaxPool2D((2, 3), padding=(0, 1), strides=(2, 3))
pool2d(X)

array([[[[ 5.,  7.],
         [13., 15.]]]])

In [72]:
### Multiple Channels

In [73]:
X = np.concatenate((X, X + 1), 1)  #construct an input with 2 channels
X

array([[[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]],

        [[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.],
         [13., 14., 15., 16.]]]])

In [74]:
#number of output channels is still 2 after pooling
pool2d = nn.MaxPool2D(3, padding=1, strides=2)
pool2d(X)


array([[[[ 5.,  7.],
         [13., 15.]],

        [[ 6.,  8.],
         [14., 16.]]]])